web:
  image: droptica/apache-php:7.1
  volumes:
    - ./app:/var/www/html
  links:
    - mysql:mysql
  environment:
    VIRTUAL_HOST: droopler.localhost, www.droopler.localhost
    DOCUMENT_ROOT: /var/www/html/web

mysql:
  image: mysql:5.6
  volumes:
    - ./app_data/database:/var/lib/mysql
    - ./docker/custom_config/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
  environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

phpmyadmin:
  image: nazarpc/phpmyadmin
  links:
    - mysql:mysql
  environment:
    VIRTUAL_HOST: phpmyadmin.droopler.localhost
